// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqpS3riGA6g6iW1lz6Mwtjt5elb63IViI',
    appId: '1:569342930813:android:037bd81990b9ac33156614',
    messagingSenderId: '569342930813',
    projectId: 'haica-10682',
    storageBucket: 'haica-10682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5upK36_lnU71mmBr9NUZBfwbz2NEM0g',
    appId: '1:569342930813:ios:328b04153c461a5e156614',
    messagingSenderId: '569342930813',
    projectId: 'haica-10682',
    storageBucket: 'haica-10682.appspot.com',
    iosBundleId: 'com.example.haica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3KWpC1m_Q3VbLA-_QO0YXXZ6NQiVgAzA',
    appId: '1:569342930813:web:9806f48ed3e74673156614',
    messagingSenderId: '569342930813',
    projectId: 'haica-10682',
    authDomain: 'haica-10682.firebaseapp.com',
    storageBucket: 'haica-10682.appspot.com',
  );
}
